name = "KhepriPOVRay"
uuid = "a0383a2d-1751-46ec-a2af-70a49b2064d3"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]
version = "0.1.0"

[deps]
KhepriBase = "4cc0fe96-1163-46f3-ba32-de1e65d9548f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
